################################
# MultiStage PipelinePractice  #
################################

FROM ubuntu as base
WORKDIR /app
COPY requirements.txt /app
COPY devops /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install -r requirements.txt && \
    cd devops

###############################################
##              Stage 2 begins               ##
###############################################
FROM gcr.io/distroless/python3
COPY --from=base /app /app
ENTRYPOINT ["python3"]
CMD ["manage.py", "runserver","0.0.0.0:8000"]
